routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index')->name('home');

//ADMIN
Route::get('/get-data-anggota/{id}', 'Web\Admin\Anggota@getDataAnggota')->name('getData');
Route::get('/get-data-anggota2/{id}', 'Web\Admin\Anggota@getDataAnggota2')->name('getData2');
Route::get('/get-data-barang/{id}', 'Web\Admin\Barang@getDataBarang')->name('getDataBarang');
Route::get('/get-data-barang2/{id}', 'Web\Admin\Barang@getDataBarang2')->name('getDataBarang2');
Route::get('/get-data-barang3/{id}', 'Web\Admin\Barang@getDataBarang3')->name('getDataBarang3');
Route::get('admin-anggota-ajax', 'Web\Admin\Anggota@dataAjax');
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Data Master
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin/anggota/hapus/{id}', 'Web\Admin\AnggotaController@hapus');
Route::resource('admin/akun', 'Web\Admin\AkunController', ['as' => 'admin']);
Route::resource('admin/ruang', 'Web\Admin\RuangController', ['as' => 'admin']);
Route::resource('admin/kategori', 'Web\Admin\KategoriController', ['as' => 'admin']);
Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/barangdetail', 'Web\Admin\BarangDetailController', ['as' => 'admin']);
//Barang Masuk
Route::resource('admin/keranjangbarangmasuk', 'Web\Admin\BarangMasukKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangmasuk', 'Web\Admin\BarangMasukController', ['as' => 'admin']);
Route::get('/inputmasuk', 'Web\Admin\BarangMasukKeranjangController@input');
//Peminjaman
Route::resource('admin/keranjangpeminjaman', 'Web\Admin\PeminjamanKeranjangController', ['as' => 'admin']);
Route::resource('admin/peminjaman', 'Web\Admin\PeminjamanController', ['as' => 'admin']);
Route::get('/inputpinjam', 'Web\Admin\PeminjamanKeranjangController@input');
Route::post('/admin/keranjangpeminjaman/tampil', 'Web\Admin\PeminjamanKeranjangController@tampil');
Route::get('/admin/peminjaman/status/{id}', 'Web\Admin\PeminjamanController@status');
//Barang Ruangan
Route::resource('admin/keranjangruangan', 'Web\Admin\RuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/ruangan', 'Web\Admin\RuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangruangan/tampil', 'Web\Admin\RuanganKeranjangController@tampil');
Route::get('/inputruangan', 'Web\Admin\RuanganKeranjangController@input');
Route::get('/admin/ruangan/tampil/{ruang}', 'Web\Admin\RuanganController@tampil');
//Barang Keluar
Route::resource('admin/keranjangkeluar', 'Web\Admin\KeluarKeranjangController', ['as' => 'admin']);
Route::resource('admin/keluar', 'Web\Admin\KeluarController', ['as' => 'admin']);
Route::post('/admin/keranjangkeluar/tampil', 'Web\Admin\KeluarKeranjangController@tampil');
Route::get('/inputkeluar', 'Web\Admin\KeluarKeranjangController@input');
//Barang Rusak Ruangan
Route::resource('admin/keranjangrusakruangan', 'Web\Admin\RusakRuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/rusakruangan', 'Web\Admin\RusakRuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangrusakruangan/tampil', 'Web\Admin\RusakRuanganKeranjangController@tampil');
Route::get('/inputrusakruangan', 'Web\Admin\RusakRuanganKeranjangController@input');
Route::get('/admin/rusakruangan/status/{id}', 'Web\Admin\RusakRuanganController@status');
//Barang Rusak Ruangan
Route::resource('admin/keranjangbarangrusak', 'Web\Admin\RusakKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangrusak', 'Web\Admin\RusakController', ['as' => 'admin']);
Route::post('/admin/keranjangbarangrusak/tampil', 'Web\Admin\RusakKeranjangController@tampil');
Route::get('/inputbarangrusak', 'Web\Admin\RusakKeranjangController@input');
Route::get('/admin/barangrusak/status/{id}', 'Web\Admin\RusakController@status');


//Sarpras
//Beranda
Route::resource('sarpras/beranda', 'Web\Sarpras\BerandaController', ['as' => 'sarpras']);


//Anggota
//Beranda
Route::resource('anggota/beranda', 'Web\Anggota\BerandaController', ['as' => 'anggota']);

app/Http/Controllers/Web/Admin/RuangController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RuangRequest;
use App\Model\Ruang;
use App\User;
use Illuminate\Http\Request;

class RuangController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $data = Ruang::orderBy('ruang', 'ASC')->get()->all();
        return view('admin.ruang.index', compact('data', 'no'));
    }

    public function create()
    {
        $anggota = User::where('role', 'anggota')->where('hapus', 0)->get()->all();
        return view('admin.ruang.create', compact('anggota'));
    }

    public function store(RuangRequest $request)
    {

        // SIMPAN DATA SISWA META
        $save = $request->all();

        Ruang::create($save);

        $notification = array(
            'message' => 'Data ruang berhasil ditambah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.ruang.index')->with($notification);
    }

    public function edit($id)
    {
        $anggota = User::where('role', 'anggota')->where('hapus', 0)->get()->all();
        $data = Ruang::findOrFail($id);
        return view('admin.ruang.edit', compact('data', 'anggota'));
    }

    public function update(RuangRequest $request, $id)
    {
        $data = Ruang::findOrFail($id);

        $dataupdate = $request->all();

        $data->update($dataupdate);

        $notification = array(
            'message' => 'Data ruang berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.ruang.index')->with($notification);
    }

    public function show($id)
    {
        $no=1;
        $data = Ruang::findOrFail($id);
        return view('admin.ruang.show', compact('data','no'));
    }

    public function destroy($id)
    {
        $data = Ruang::findOrFail($id);

        $notification = array(
            'message' => 'Data ruangan berhasil dihapus.',
            'alert-type' => 'error'
        );

        $data->delete();

        return redirect()->route('admin.ruang.index')->with($notification);
    }
}

resources/views/admin/ruang/create.blade.php
@extends('layouts.admin')
@section('title', 'Ruang')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Ruang
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Ruang</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.ruang.store') }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Ruang</label>
                            <div class="col-sm-10">
                                <input type="text" name="ruang" class="form-control" placeholder="Ruang : Ex: Lab TKJ">
                                <small class="text-danger">{{ $errors->first('ruang') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tahun" class="col-sm-2 control-label">P. Jawab</label>

                            <div class="col-sm-10">
                                <select class="form-control" name="user_id">
                                    @foreach ($anggota as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/ruang')}}" class="btn btn-default  pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/ruang/edit.blade.php
@extends('layouts.admin')
@section('title', 'Ruang')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Ruang
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Ruang</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.ruang.update', $data->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Ruang</label>
                            <div class="col-sm-10">
                                <input type="text" value="{{ $data->ruang }}" name="ruang" class="form-control" placeholder="Ruang : Ex: Lab TKJ">
                                <small class="text-danger">{{ $errors->first('ruang') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tahun" class="col-sm-2 control-label">P. Jawab</label>

                            <div class="col-sm-10">
                                <select class="form-control" name="user_id">
                                    <option value="{{ $data->user->id }}">{{ $data->user->name }}</option>
                                    @foreach ($anggota as $item)
                                        <option value="{{ $item->id }}">{{ $item->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/ruang')}}" class="btn btn-default pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/ruang/index.blade.php
@extends('layouts.admin')
@section('title', 'Ruang')
@section('content')


<div class="container">

    <section class="content-header">
        <h1>
            Ruang
        </h1>
    </section><br><br>

    <div class="row">
        
        <div class="col-md-4">
            <a href="{{ route('admin.ruang.create') }}" class="btn btn-primary">+ Ruang</a><br><br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Ruang</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Ruang</th>
                                <th>Penanggung Jawab</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->ruang}}</td>
                                <td>{{ $item->user->name}}</td>
                                <td align="center" width="200px">
                                    @if($item->ruangan->count()===0)
                                        <form action="{{ route('admin.ruang.destroy',$item->id) }}" method="POST">
                                            <a class="btn btn-success" href="{{ route('admin.ruang.edit',$item->id) }}" alt="Edit"><i class="fa fa-edit"></i></a>

                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger" alt="Hapus"><i class="fa fa-trash"></i></button>
                                        </form>
                                    @else
                                        <a class="btn btn-primary" href="{{ route('admin.ruang.show',$item->id) }}" alt="Lihat"><i class="fa fa-eye"></i></a>
                                        <a class="btn btn-success" href="{{ route('admin.ruang.edit',$item->id) }}" alt="Edit"><i class="fa fa-edit"></i></a>
                                    @endif
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/admin/ruang/show.blade.php
@extends('layouts.admin')
@section('title', 'Barang Ruangan')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Barang Ruangan {{ $data->ruang }}
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Barang</th>
                                <th>Jumlah</th>
                                <th>Jumlah Rusak</th>
                                <th>Tanggal Masuk</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data->ruangan as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->barang_detail->barang->barang }} {{ $item->barang_detail->merk }}</td>
                                <td>{{ $item->jumlah }}</td>
                                <td>{{ $item->jumlah_rusak }}</td>
                                <td>{{ $item->tanggal_masuk->format('d-m-Y')}}</td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection