routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index')->name('home');

//ADMIN
Route::get('/get-data-anggota/{id}', 'Web\Admin\Anggota@getDataAnggota')->name('getData');
Route::get('/get-data-anggota2/{id}', 'Web\Admin\Anggota@getDataAnggota2')->name('getData2');
Route::get('/get-data-barang/{id}', 'Web\Admin\Barang@getDataBarang')->name('getDataBarang');
Route::get('/get-data-barang2/{id}', 'Web\Admin\Barang@getDataBarang2')->name('getDataBarang2');
Route::get('/get-data-barang3/{id}', 'Web\Admin\Barang@getDataBarang3')->name('getDataBarang3');
Route::get('admin-anggota-ajax', 'Web\Admin\Anggota@dataAjax');
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Data Master
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin/anggota/hapus/{id}', 'Web\Admin\AnggotaController@hapus');
Route::resource('admin/akun', 'Web\Admin\AkunController', ['as' => 'admin']);
Route::resource('admin/ruang', 'Web\Admin\RuangController', ['as' => 'admin']);
Route::resource('admin/kategori', 'Web\Admin\KategoriController', ['as' => 'admin']);
Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/barangdetail', 'Web\Admin\BarangDetailController', ['as' => 'admin']);
//Barang Masuk
Route::resource('admin/keranjangbarangmasuk', 'Web\Admin\BarangMasukKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangmasuk', 'Web\Admin\BarangMasukController', ['as' => 'admin']);
Route::get('/inputmasuk', 'Web\Admin\BarangMasukKeranjangController@input');
//Peminjaman
Route::resource('admin/keranjangpeminjaman', 'Web\Admin\PeminjamanKeranjangController', ['as' => 'admin']);
Route::resource('admin/peminjaman', 'Web\Admin\PeminjamanController', ['as' => 'admin']);
Route::get('/inputpinjam', 'Web\Admin\PeminjamanKeranjangController@input');
Route::post('/admin/keranjangpeminjaman/tampil', 'Web\Admin\PeminjamanKeranjangController@tampil');
Route::get('/admin/peminjaman/status/{id}', 'Web\Admin\PeminjamanController@status');
//Barang Ruangan
Route::resource('admin/keranjangruangan', 'Web\Admin\RuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/ruangan', 'Web\Admin\RuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangruangan/tampil', 'Web\Admin\RuanganKeranjangController@tampil');
Route::get('/inputruangan', 'Web\Admin\RuanganKeranjangController@input');
Route::get('/admin/ruangan/tampil/{ruang}', 'Web\Admin\RuanganController@tampil');
//Barang Keluar
Route::resource('admin/keranjangkeluar', 'Web\Admin\KeluarKeranjangController', ['as' => 'admin']);
Route::resource('admin/keluar', 'Web\Admin\KeluarController', ['as' => 'admin']);
Route::post('/admin/keranjangkeluar/tampil', 'Web\Admin\KeluarKeranjangController@tampil');
Route::get('/inputkeluar', 'Web\Admin\KeluarKeranjangController@input');
//Barang Rusak Ruangan
Route::resource('admin/keranjangrusakruangan', 'Web\Admin\RusakRuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/rusakruangan', 'Web\Admin\RusakRuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangrusakruangan/tampil', 'Web\Admin\RusakRuanganKeranjangController@tampil');
Route::get('/inputrusakruangan', 'Web\Admin\RusakRuanganKeranjangController@input');
Route::get('/admin/rusakruangan/status/{id}', 'Web\Admin\RusakRuanganController@status');
//Barang Rusak Ruangan
Route::resource('admin/keranjangbarangrusak', 'Web\Admin\RusakKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangrusak', 'Web\Admin\RusakController', ['as' => 'admin']);
Route::post('/admin/keranjangbarangrusak/tampil', 'Web\Admin\RusakKeranjangController@tampil');
Route::get('/inputbarangrusak', 'Web\Admin\RusakKeranjangController@input');
Route::get('/admin/barangrusak/status/{id}', 'Web\Admin\RusakController@status');


//Sarpras
//Beranda
Route::resource('sarpras/beranda', 'Web\Sarpras\BerandaController', ['as' => 'sarpras']);


//Anggota
//Beranda
Route::resource('anggota/beranda', 'Web\Anggota\BerandaController', ['as' => 'anggota']);

app/Http/Controllers/Web/Admin/BarangMasukController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\BarangMasukRequest;
use App\Model\Barang;
use App\Model\BarangDetail;
use App\Model\BarangMasuk;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BarangMasukController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $data = BarangMasuk::orderBy('tanggal_masuk', 'DESC')->get()->all();
        return view('admin.barangmasuk.data.index', compact('data', 'no'));
    }

    public function show($id)
    {
        $data = BarangMasuk::findOrFail($id);
        return view('admin.barangmasuk.data.show', compact('data'));
    }

    public function edit($id)
    {
        $barang = Barang::orderBy('barang', 'ASC')->get()->all();
        $data = BarangMasuk::findOrFail($id);
        return view('admin.barangmasuk.data.edit', compact('data', 'barang'));
    }

    public function update(BarangMasukRequest $request, $id)
    {
        
        $data = BarangMasuk::findOrFail($id);

        $dataupdate = $request->all();

        if ($data->jumlah == $request->jumlah) {
            $bd = BarangDetail::where('kode_barang', $data->kode_barang)->get()->first();
            $bdupdate = $request->all();
            $bdupdate['jumlah'] = $bd->jumlah;
            $bd->update($bdupdate);
        } else if ($data->jumlah > $request->jumlah) {
            $bd = BarangDetail::where('kode_barang', $data->kode_barang)->get()->first();
            $bdupdate = $request->all();
            $kurang = $data->jumlah - $request->jumlah;
            $bdupdate['jumlah'] = $bd->jumlah - $kurang;
            $bd->update($bdupdate);
        } else {
            $bd = BarangDetail::where('kode_barang', $data->kode_barang)->get()->first();
            $bdupdate = $request->all();
            $lebih = $request->jumlah - $data->jumlah;
            $bdupdate['jumlah'] = $bd->jumlah + $lebih;
            $bd->update($bdupdate);
        }

        $data->update($dataupdate);

        $notification = array(
            'message' => 'Data barang masuk berhasil diubah.',
            'alert-type' => 'success'
        );

        return redirect()->route('admin.barangmasuk.index')->with($notification);
    }
}

resources/views/admin/barangmasuk/data/edit.blade.php
@extends('layouts.admin')
@section('title', 'Barang Masuk')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Barang Masuk
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Barang Masuk</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.barangmasuk.update', $data->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Kode Barang</label>
                            <div class="col-sm-10">
                                <input type="text" name="kode_barang" value="{{ $data->kode_barang }}" readonly class="form-control" placeholder="Jumlah">
                                <small class="text-danger">{{ $errors->first('jumlah') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="tahun" class="col-sm-2 control-label">Barang</label>

                            <div class="col-sm-10">
                                <select class="form-control" name="barang_id">
                                    <option value="{{ $data->barang_id }}">{{ $data->barang->barang}}</option>
                                    @foreach ($barang as $item)
                                        <option value="{{ $item->id }}">{{ $item->barang}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Jumlah</label>
                            <div class="col-sm-10">
                                <input type="number" value="{{ $data->jumlah }}" name="jumlah" id="txt1" onkeyup="sum();" class="form-control" placeholder="Jumlah">
                                <small class="text-danger">{{ $errors->first('jumlah') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Harga Satuan</label>
                            <div class="col-sm-10">
                                <input type="number" value="{{ $data->harga_satuan }}" name="harga_satuan" id="txt2" onkeyup="sum();" class="form-control" placeholder="Harga Satuan">
                                <small class="text-danger">{{ $errors->first('harga_satuan') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Harga Total</label>
                            <div class="col-sm-10">
                                <input type="number" value="{{ $data->harga_total }}" name="harga_total" id="txt3" readonly class="form-control" placeholder="Harga Total">
                                <small class="text-danger">{{ $errors->first('harga_total') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Merk</label>
                            <div class="col-sm-10">
                                <input type="text" name="merk" value="{{ $data->merk }}" class="form-control" placeholder="Merk">
                                <small class="text-danger">{{ $errors->first('merk') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Sumber Dana</label>
                            <div class="col-sm-10">
                                <input type="text" name="sumber_dana" value="{{ $data->sumber_dana }}" class="form-control" placeholder="Sumber Dana">
                                <small class="text-danger">{{ $errors->first('sumber_dana') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Tanggal Masuk</label>
                            <div class="col-sm-10">
                                <input type="date" name="tanggal_masuk" value="{{ $data->tanggal_masuk->format('Y-m-d') }}" class="form-control" placeholder="Tanggal Masuk">
                                <small class="text-danger">{{ $errors->first('tanggal_masuk') }}</small>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="tahun" class="col-sm-2 control-label">Keterangan</label>

                            <div class="col-sm-10">
                                <div class="box-body pad">
                                    <textarea class="textarea" name="keterangan" placeholder="Keterangan" id="isi" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px">{{ $data->keterangan }}</textarea>
                                </div>
                                <small class="text-danger">{{ $errors->first('keterangan') }}</small>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/barangmasuk')}}" class="btn btn-default pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script type="text/javascript">

        function sum() {
            var txtFirstNumberValue = document.getElementById('txt1').value;
            var txtSecondNumberValue = document.getElementById('txt2').value;
            var result = parseFloat(txtFirstNumberValue) * parseFloat(txtSecondNumberValue);
            if (!isNaN(result)) {
                document.getElementById('txt3').value = result;
            }
        }

    </script>

@endpush
@endsection

resources/views/admin/barangmasuk/data/index.blade.php
@extends('layouts.admin')
@section('title', 'Barang Masuk')
@section('content')


<div class="container">

    <section class="content-header">
        <h1>
            Barang Masuk
        </h1>
    </section><br><br>

    <div class="row">
        
        <div class="col-md-4">
            <a href="{{ route('admin.barangmasuk.create') }}" class="btn btn-primary">+ Barang Masuk</a><br><br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Barang Masuk</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Kode</th>
                                <th>Barang</th>
                                <th>Merk</th>
                                <th>Jumlah</th>
                                <th>Harga Satuan</th>
                                <th>Tanggal Masuk</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->kode_barang }}</td>
                                <td>{{ $item->barang->barang }}</td>
                                <td>{{ $item->merk }}</td>
                                <td>{{ $item->jumlah }}</td>
                                <td>Rp. {{ number_format($item->harga_satuan, 0, ".", ".") }},-</td>
                                <td>{{ $item->tanggal_masuk->format('d-m-Y') }}</td>
                                <td align="center" width="200px">
                                    <a class="btn btn-primary" href="{{ route('admin.barangmasuk.show',$item->id) }}" alt="Lihat"><i class="fa fa-eye"></i></a>
                                    <a class="btn btn-success" href="{{ route('admin.barangmasuk.edit',$item->id) }}" alt="Edit"><i class="fa fa-edit"></i></a>
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/admin/barangmasuk/data/show.blade.php
@extends('layouts.admin')
@section('title', 'Barang Masuk')
@section('content')
<div class="container">

    <section class="content-header">
        <h1>
            Barang Masuk
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Barang - {{$data->barang->barang}}</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <div class="col-md-8">
                        <table id="example1" class="table table-bordered table-striped">
                            <tbody>
                                <tr>
                                    <td>Kode Barang</td>
                                    <td>{{$data->kode_barang}}</td>
                                </tr>
                                <tr>
                                    <td>Nama Barang</td>
                                    <td>{{$data->barang->barang}}</td>
                                </tr>
                                <tr>
                                    <td>Merk</td>
                                    <td>{{$data->merk}}</td>
                                </tr>
                                <tr>
                                    <td>Jumlah</td>
                                    <td>{{$data->jumlah}}</td>
                                </tr>
                                <tr>
                                    <td>Harga Satuan</td>
                                    <td>Rp. {{ number_format($data->harga_satuan, 0, ".", ".")}},-</td>
                                </tr>
                                <tr>
                                    <td>Total</td>
                                    <td>Rp. {{ number_format($data->harga_total, 0, ".", ".")}},-</td>
                                </tr>
                                <tr>
                                    <td>Sumber Dana</td>
                                    <td>{{$data->sumber_dana}}</td>
                                </tr>
                                <tr>
                                    <td>Tanggal Masuk</td>
                                    <td>{{$data->tanggal_masuk->format('d-m-Y')}}</td>
                                </tr>
                                <tr>
                                    <td>Keterangan</td>
                                    <td>{!! $data->keterangan !!}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    @php
                        $harga = "Rp. ".number_format($data->harga_satuan, 0, ".", ".").",-";
                        $nama_barang = $data->barang->barang;
                        $tanggal = $data->tanggal_masuk->format('d-m-Y');
                    @endphp
                    <div class="col-md-4" align="center">
                        <img src="data:image/png;base64, {!! base64_encode(QrCode::format('png')
                                // ->merge('itlabil/image/default/logo.png', 0.5, true)
                                ->size(250)->errorCorrection('H')
                                ->generate("$data->kode_barang\nNama : $nama_barang\nMerk : $data->merk\nJumlah : $data->jumlah\nHarga : $harga\nSumber Dana : $data->sumber_dana\nTanggal Masuk : $tanggal\nKeterangan : $data->keterangan")) !!} ">
                    </div>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <a href="{{url('admin/barangmasuk')}}" class="btn btn-default">Kembali</a>
                    <a class="btn btn-success" href="{{ route('admin.barangmasuk.edit',$data->id) }}">Ubah</a>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection