routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index')->name('home');

//ADMIN
Route::get('/get-data-anggota/{id}', 'Web\Admin\Anggota@getDataAnggota')->name('getData');
Route::get('/get-data-anggota2/{id}', 'Web\Admin\Anggota@getDataAnggota2')->name('getData2');
Route::get('/get-data-barang/{id}', 'Web\Admin\Barang@getDataBarang')->name('getDataBarang');
Route::get('/get-data-barang2/{id}', 'Web\Admin\Barang@getDataBarang2')->name('getDataBarang2');
Route::get('/get-data-barang3/{id}', 'Web\Admin\Barang@getDataBarang3')->name('getDataBarang3');
Route::get('admin-anggota-ajax', 'Web\Admin\Anggota@dataAjax');
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Data Master
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin/anggota/hapus/{id}', 'Web\Admin\AnggotaController@hapus');
Route::resource('admin/akun', 'Web\Admin\AkunController', ['as' => 'admin']);
Route::resource('admin/ruang', 'Web\Admin\RuangController', ['as' => 'admin']);
Route::resource('admin/kategori', 'Web\Admin\KategoriController', ['as' => 'admin']);
Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/barangdetail', 'Web\Admin\BarangDetailController', ['as' => 'admin']);
//Barang Masuk
Route::resource('admin/keranjangbarangmasuk', 'Web\Admin\BarangMasukKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangmasuk', 'Web\Admin\BarangMasukController', ['as' => 'admin']);
Route::get('/inputmasuk', 'Web\Admin\BarangMasukKeranjangController@input');
//Peminjaman
Route::resource('admin/keranjangpeminjaman', 'Web\Admin\PeminjamanKeranjangController', ['as' => 'admin']);
Route::resource('admin/peminjaman', 'Web\Admin\PeminjamanController', ['as' => 'admin']);
Route::get('/inputpinjam', 'Web\Admin\PeminjamanKeranjangController@input');
Route::post('/admin/keranjangpeminjaman/tampil', 'Web\Admin\PeminjamanKeranjangController@tampil');
Route::get('/admin/peminjaman/status/{id}', 'Web\Admin\PeminjamanController@status');
//Barang Ruangan
Route::resource('admin/keranjangruangan', 'Web\Admin\RuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/ruangan', 'Web\Admin\RuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangruangan/tampil', 'Web\Admin\RuanganKeranjangController@tampil');
Route::get('/inputruangan', 'Web\Admin\RuanganKeranjangController@input');
Route::get('/admin/ruangan/tampil/{ruang}', 'Web\Admin\RuanganController@tampil');
//Barang Keluar
Route::resource('admin/keranjangkeluar', 'Web\Admin\KeluarKeranjangController', ['as' => 'admin']);
Route::resource('admin/keluar', 'Web\Admin\KeluarController', ['as' => 'admin']);
Route::post('/admin/keranjangkeluar/tampil', 'Web\Admin\KeluarKeranjangController@tampil');
Route::get('/inputkeluar', 'Web\Admin\KeluarKeranjangController@input');
//Barang Rusak Ruangan
Route::resource('admin/keranjangrusakruangan', 'Web\Admin\RusakRuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/rusakruangan', 'Web\Admin\RusakRuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangrusakruangan/tampil', 'Web\Admin\RusakRuanganKeranjangController@tampil');
Route::get('/inputrusakruangan', 'Web\Admin\RusakRuanganKeranjangController@input');
Route::get('/admin/rusakruangan/status/{id}', 'Web\Admin\RusakRuanganController@status');
//Barang Rusak Ruangan
Route::resource('admin/keranjangbarangrusak', 'Web\Admin\RusakKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangrusak', 'Web\Admin\RusakController', ['as' => 'admin']);
Route::post('/admin/keranjangbarangrusak/tampil', 'Web\Admin\RusakKeranjangController@tampil');
Route::get('/inputbarangrusak', 'Web\Admin\RusakKeranjangController@input');
Route::get('/admin/barangrusak/status/{id}', 'Web\Admin\RusakController@status');


//Sarpras
//Beranda
Route::resource('sarpras/beranda', 'Web\Sarpras\BerandaController', ['as' => 'sarpras']);


//Anggota
//Beranda
Route::resource('anggota/beranda', 'Web\Anggota\BerandaController', ['as' => 'anggota']);

app/Http/Controllers/Web/Admin/KeluarController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Model\Keluar;
use Illuminate\Http\Request;

class KeluarController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $data = Keluar::orderBy('id', 'DESC')->get()->all();
        return view('admin.keluar.data.index', compact('data', 'no'));
    }
}

resources/views/admin/keluar/keranjang/create.blade.php
@extends('layouts.admin')
@section('title', 'Keranjang Barang Keluar')
@section('content')
<script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>
<div class="container">

    <section class="content-header">
        <h1>
            Keranjang Barang Keluar
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                {{-- <div class="box-header with-border">
                    <h3 class="box-title">Keranjang Peminjaman</h3>
                </div> --}}
                <div class="box-body" style="overflow-x:auto;">
                        <div class="row">
                            <div class="col-md-6">
                                <table class="table">
                                    <tr>
                                        <td>Nama Peminjam</td>
                                        <td>: {{ $users->name }}</td>
                                    </tr>
                                    <tr>
                                        <td>Tanggal Keluar</td>
                                        <td>: {{ tanggal_local(Carbon\Carbon::parse($tanggal_keluar)->format('Y-m-d')) }}</td>
                                    </tr>
                                    <tr>
                                        <td>Keterangan</td>
                                        <td>: {{ $keterangan }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <label for="video" style="form-control float:top" class="control-label">Scan QR Code</label><br>
                                            <center><video name="video" id="preview" style="width: 400px"></video></center>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <div class="table-responsive">
                                    <form class="form-horizontal" action="{{ route('admin.keranjangkeluar.store') }}" method="post">
                                        @csrf
                                        <br>
                                        <div class="input_fields_wrap">
                                            <button class="add_field_button btn btn-primary">Tambah Barang</button><br><br>
                                        </div>
                                        <input type="hidden" value="{{ $user_id }}" name="user_id" class="form-control" required>
                                        <input type="hidden" value="{{ $tanggal_keluar }}" name="tanggal_keluar" class="form-control" required>
                                        <input type="hidden" value="{{ $keterangan }}" name="keterangan" class="form-control" required>
                                        <br><br>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Simpan</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
      </div>
</div>

@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function() {
            var max_fields      = 100; //maximum input boxes allowed
            var wrapper   		= $(".input_fields_wrap"); //Fields wrapper
            var add_button      = $(".add_field_button"); //Add button ID
        
            var x = 1; //initlal text box count
            $(add_button).click(function(e){ //on add input button click
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                    
                    let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
                    scanner.addListener('scan', function (content) {
                        var kode = content.substring(0, 10);
                        //$('#barang_id'+x).val(kode);
                        $.get("{{url ('get-data-barang2') }}"+'/'+kode,function(data){
                            $('#nama_barang'+x).val(data.nama);
                            $('#barang_id'+x).val(data.id);
                            var max = document.getElementById("number_id"+x);
                            max.setAttribute("max", data.max)
                            max.setAttribute("placeholder", "Jumlah Maksimal "+data.max)
                        });
                    });
                    Instascan.Camera.getCameras().then(function (cameras) {
                        if (cameras.length > 0) {
                            scanner.start(cameras[0]);
                        } else {
                            console.error('No cameras found.');
                        }
                    }).catch(function (e) {
                        console.error(e);
                    });

                    x++; //text box increment
                    $(wrapper).append('<div><select class="form-control" id="barang'+x+'"><option>Pilih Barang</option>@foreach ($barang as $data)@foreach ($data->barang_detail as $item)<option value="{{ $item->kode_barang }}">{{ $item->barang->barang}} {{ $item->merk}} ({{ $item->jumlah}})</option>@endforeach @endforeach</select><label for="">Barang</label><input type="hidden" id="barang_id'+x+'" name="barang_id[]"><input type="text" id="nama_barang'+x+'" name="nama_barang[]" class="form-control" required placeholder="Barang" required readonly><br><input id="number_id'+x+'" type="number" name="jumlah[]" class="form-control" required placeholder="Masukan Jumlah" required></td></tr></table><a href="#" class="remove_field">Remove</a><hr></div>');
                    
                    $("#barang"+x).change(function() {
                        $.get("{{url ('get-data-barang2') }}"+'/'+$(this).val(),function(data){
                            $('#nama_barang'+x).val(data.nama);
                            $('#barang_id'+x).val(data.id);
                            var max = document.getElementById("number_id"+x);
                            max.setAttribute("max", data.max)
                            max.setAttribute("placeholder", "Jumlah Maksimal "+data.max)
                        });
                    }); 
                }
            });

            $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
    </script>
@endsection

resources/views/admin/keluar/keranjang/edit.blade.php
@extends('layouts.admin')
@section('title', 'Keranjang Barang Keluar')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Keranjang Barang Keluar
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Keranjang Barang Keluar</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.keranjangkeluar.update', $data->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nama Peminjam</label>
                            <div class="col-sm-10">
                                <input type="text" value="{{ $data->user->name }}" class="form-control" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Barang</label>
                            <div class="col-sm-10">
                                <input type="text" value="{{ $data->barang_detail->barang->barang }} {{ $data->barang_detail->merk }}" class="form-control" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Jumlah</label>
                            <div class="col-sm-10">
                                <input type="number" value="{{ $data->jumlah }}" name="jumlah" class="form-control" placeholder="{{ $data->jumlah_pinjam+$data->barang_detail->jumlah }}">
                                <small class="text-danger">{{ $errors->first('jumlah') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Tanggal Keluar</label>
                            <div class="col-sm-10">
                                <input type="date" name="tanggal_keluar" value="{{ $data->tanggal_keluar->format('Y-m-d') }}" class="form-control" placeholder="Tanggal Masuk">
                                <small class="text-danger">{{ $errors->first('tanggal_keluar') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Keterangan</label>
                            <div class="col-sm-10">
                                <input type="text" name="keterangan" value="{{ $data->keterangan }}" class="form-control" placeholder="Tanggal Masuk">
                                <small class="text-danger">{{ $errors->first('keterangan') }}</small>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/keranjangkeluar')}}" class="btn btn-default pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script type="text/javascript">

        function sum() {
            var txtFirstNumberValue = document.getElementById('txt1').value;
            var txtSecondNumberValue = document.getElementById('txt2').value;
            var result = parseFloat(txtFirstNumberValue) * parseFloat(txtSecondNumberValue);
            if (!isNaN(result)) {
                document.getElementById('txt3').value = result;
            }
        }

    </script>

@endpush
@endsection

resources/views/admin/keluar/keranjang/index.blade.php
@extends('layouts.admin')
@section('title', 'Keranjang Barang Keluar')
@section('content')
<script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>

<div class="container">

    <section class="content-header">
        <h1>
            Keranjang Barang Keluar
        </h1>
    </section><br><br>

    <div class="row">
        
        <div class="col-md-4">
            <button class="btn btn-success" data-toggle="modal" data-target="#tambah">Tambah Data</button><br><br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Keranjang Barang Keluar</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama Peminjam</th>
                                <th>Barang</th>
                                <th>Jumlah</th>
                                <th>Tanggal Keluar</th>
                                <th>Keterangan</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->user->name }}</td>
                                <td>{{ $item->barang_detail->barang->barang }} {{ $item->barang_detail->merk }}</td>
                                <td>{{ $item->jumlah }}</td>
                                <td>{{ $item->tanggal_keluar->format('d-m-Y')}}</td>
                                <td>{{ $item->keterangan }}</td>
                                <td>
                                    @if($item->status==='Telah disetujui')
                                        <span class="label label-info">{{ $item->status }}</span>
                                    @else
                                        <span class="label label-warning">{{ $item->status }}</span>
                                    @endif
                                </td>
                                <td align="center" width="200px">
                                    @if($item->status==='Telah disetujui')
                                    <form action="{{ route('admin.keranjangkeluar.destroy',$item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger" alt="Hapus"><i class="fa fa-trash"></i></button>
                                    </form>
                                    @else
                                    <form action="{{ route('admin.keranjangkeluar.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.keranjangkeluar.edit',$item->id) }}" alt="Edit"><i class="fa fa-edit"></i></a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger" alt="Hapus"><i class="fa fa-trash"></i></button>
                                    </form>
                                    @endif
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
                <div class="box-header with-border" align="center">
                    <a href="/inputkeluar" class="btn btn-primary">Masukan Semua Data</a>
                </div>
            </div>
        </div>

        <div id="tambah" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Masukan Data</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="/admin/keranjangkeluar/tampil" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="video" style="form-control float:top" class="control-label">Scan QR Code</label><br>
                                <center><video name="video" id="preview" style="width: 400px"></video></center>
                            </div>
                            <div class="form-group">
                                <label for="">Pilih Peminjam</label>
                                <select name="anggota" class="myselect form-control" id="anggota"  style="width:100%">
                                    <option value="" selected disabled>Pilih Peminjam</option>
                                    @foreach ($users as $user)
                                        <option value="{{$user->id}}">{{$user->no_induk}} - {{$user->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="">Nama Peminjam</label>
                                <input type="hidden" name="no_induk" id="no_induk">
                                <input type="hidden" id="user_id" name="user_id" class="form-control"  required>
                                <input type="text" id="nama" readonly name="nama" class="form-control"  required>
                            </div>
                            <div class="form-group">
                                <label for="">Tanggal Keluar</label>
                                <input type="date" name="tanggal_keluar" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="">Keterangan</label>
                                <input type="text" id="keterangan" name="keterangan" class="form-control">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Lanjut</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<script type="text/javascript">
    let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
    scanner.addListener('scan', function (content) {
        var no_induk = content.substring(0, 6);
        $('#no_induk').val(no_induk);
        $.get("{{url ('get-data-anggota2') }}"+'/'+no_induk,function(data){
            $('#user_id').val(data.id);
            $('#nama').val(data.name);
        });
    });
    Instascan.Camera.getCameras().then(function (cameras) {
        if (cameras.length > 0) {
            scanner.start(cameras[0]);
        } else {
            console.error('No cameras found.');
        }
    }).catch(function (e) {
        console.error(e);
    });
</script>
@endsection

@section('script')
<script type="text/javascript">
    $("#anggota").change(function() {
         $.ajax({
             url: '/get-data-anggota/' + $(this).val(),
             type: 'get',
             data: {},
             success: function(data) {
             if (data.success == true) {
                 $('#nama').val(data.name);
                 $('#no_induk').val(data.no_induk);
                 $('#user_id').val(data.id);
             } else {
                 alert('Cannot find info');
             }
  
             },
             error: function(jqXHR, textStatus, errorThrown) {}
         });
     }); 
  </script>
@endsection