routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/login');
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', 'HomeController@index')->name('home');

//ADMIN
Route::get('/get-data-anggota/{id}', 'Web\Admin\Anggota@getDataAnggota')->name('getData');
Route::get('/get-data-anggota2/{id}', 'Web\Admin\Anggota@getDataAnggota2')->name('getData2');
Route::get('/get-data-barang/{id}', 'Web\Admin\Barang@getDataBarang')->name('getDataBarang');
Route::get('/get-data-barang2/{id}', 'Web\Admin\Barang@getDataBarang2')->name('getDataBarang2');
Route::get('/get-data-barang3/{id}', 'Web\Admin\Barang@getDataBarang3')->name('getDataBarang3');
Route::get('admin-anggota-ajax', 'Web\Admin\Anggota@dataAjax');
//Beranda
Route::resource('admin/beranda', 'Web\Admin\BerandaController', ['as' => 'admin']);
//Data Master
Route::resource('admin/anggota', 'Web\Admin\AnggotaController', ['as' => 'admin']);
Route::get('admin/anggota/hapus/{id}', 'Web\Admin\AnggotaController@hapus');
Route::resource('admin/akun', 'Web\Admin\AkunController', ['as' => 'admin']);
Route::resource('admin/ruang', 'Web\Admin\RuangController', ['as' => 'admin']);
Route::resource('admin/kategori', 'Web\Admin\KategoriController', ['as' => 'admin']);
Route::resource('admin/barang', 'Web\Admin\BarangController', ['as' => 'admin']);
Route::resource('admin/barangdetail', 'Web\Admin\BarangDetailController', ['as' => 'admin']);
//Barang Masuk
Route::resource('admin/keranjangbarangmasuk', 'Web\Admin\BarangMasukKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangmasuk', 'Web\Admin\BarangMasukController', ['as' => 'admin']);
Route::get('/inputmasuk', 'Web\Admin\BarangMasukKeranjangController@input');
//Peminjaman
Route::resource('admin/keranjangpeminjaman', 'Web\Admin\PeminjamanKeranjangController', ['as' => 'admin']);
Route::resource('admin/peminjaman', 'Web\Admin\PeminjamanController', ['as' => 'admin']);
Route::get('/inputpinjam', 'Web\Admin\PeminjamanKeranjangController@input');
Route::post('/admin/keranjangpeminjaman/tampil', 'Web\Admin\PeminjamanKeranjangController@tampil');
Route::get('/admin/peminjaman/status/{id}', 'Web\Admin\PeminjamanController@status');
//Barang Ruangan
Route::resource('admin/keranjangruangan', 'Web\Admin\RuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/ruangan', 'Web\Admin\RuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangruangan/tampil', 'Web\Admin\RuanganKeranjangController@tampil');
Route::get('/inputruangan', 'Web\Admin\RuanganKeranjangController@input');
Route::get('/admin/ruangan/tampil/{ruang}', 'Web\Admin\RuanganController@tampil');
//Barang Keluar
Route::resource('admin/keranjangkeluar', 'Web\Admin\KeluarKeranjangController', ['as' => 'admin']);
Route::resource('admin/keluar', 'Web\Admin\KeluarController', ['as' => 'admin']);
Route::post('/admin/keranjangkeluar/tampil', 'Web\Admin\KeluarKeranjangController@tampil');
Route::get('/inputkeluar', 'Web\Admin\KeluarKeranjangController@input');
//Barang Rusak Ruangan
Route::resource('admin/keranjangrusakruangan', 'Web\Admin\RusakRuanganKeranjangController', ['as' => 'admin']);
Route::resource('admin/rusakruangan', 'Web\Admin\RusakRuanganController', ['as' => 'admin']);
Route::post('/admin/keranjangrusakruangan/tampil', 'Web\Admin\RusakRuanganKeranjangController@tampil');
Route::get('/inputrusakruangan', 'Web\Admin\RusakRuanganKeranjangController@input');
Route::get('/admin/rusakruangan/status/{id}', 'Web\Admin\RusakRuanganController@status');
//Barang Rusak Ruangan
Route::resource('admin/keranjangbarangrusak', 'Web\Admin\RusakKeranjangController', ['as' => 'admin']);
Route::resource('admin/barangrusak', 'Web\Admin\RusakController', ['as' => 'admin']);
Route::post('/admin/keranjangbarangrusak/tampil', 'Web\Admin\RusakKeranjangController@tampil');
Route::get('/inputbarangrusak', 'Web\Admin\RusakKeranjangController@input');
Route::get('/admin/barangrusak/status/{id}', 'Web\Admin\RusakController@status');


//Sarpras
//Beranda
Route::resource('sarpras/beranda', 'Web\Sarpras\BerandaController', ['as' => 'sarpras']);


//Anggota
//Beranda
Route::resource('anggota/beranda', 'Web\Anggota\BerandaController', ['as' => 'anggota']);

app/Http/Controllers/Web/Admin/RusakRuanganController.php
<?php

namespace App\Http\Controllers\Web\Admin;

use App\Http\Controllers\Controller;
use App\Model\Ruangan;
use App\Model\RusakRuangan;
use Illuminate\Http\Request;

class RusakRuanganController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
        $this->middleware('role:admin');
    }

    public function index()
    {
        $no = 1;
        $data = RusakRuangan::orderBy('id', 'DESC')->get();
        return view('admin.rusakruangan.data.index', compact('data', 'no'));
    }

    public function status($id)
    {
        $data = RusakRuangan::findOrFail($id);
        $dataup['status'] = 'Sudah diperbaiki';
        $data->update($dataup);

        $bd = Ruangan::where('id', $data->ruangan_id)->first();
        $bdup['jumlah'] = $data->jumlah + $bd->jumlah;
        $bdup['jumlah_rusak'] = $bd->jumlah_rusak - $data->jumlah;
        $bd->update($bdup);

        $notification = array(
            'message' => 'Barang Rusak berhasil diperbaiki.',
            'alert-type' => 'success'
        );

        return redirect()->back()->with($notification);
    }

    public function show($id)
    {
        $data = RusakRuangan::findOrFail($id);
        return view('admin.rusakruangan.data.show', compact('data'));
    }
}

resources/views/admin/rusakruangan/keranjang/create.blade.php
@extends('layouts.admin')
@section('title', 'Keranjang Rusak Ruangan')
@section('content')
<script src="https://rawgit.com/schmich/instascan-builds/master/instascan.min.js"></script>
<div class="container">

    <section class="content-header">
        <h1>
            Keranjang Rusak Ruangan
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                {{-- <div class="box-header with-border">
                    <h3 class="box-title">Keranjang Peminjaman</h3>
                </div> --}}
                <div class="box-body" style="overflow-x:auto;">
                        <div class="row">
                            <div class="col-md-6">
                                <table class="table">
                                    <tr>
                                        <td>Ruang</td>
                                        <td>: {{ $ruang->ruang }}</td>
                                    </tr>
                                    <tr>
                                        <td>Tanggal Rusak</td>
                                        <td>: {{ tanggal_local(Carbon\Carbon::parse($tanggal_rusak)->format('Y-m-d')) }}</td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <label for="video" style="form-control float:top" class="control-label">Scan QR Code</label><br>
                                            <center><video name="video" id="preview" style="width: 400px"></video></center>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <div class="table-responsive">
                                    <form class="form-horizontal" action="{{ route('admin.keranjangrusakruangan.store') }}" method="post">
                                        @csrf
                                        <br>
                                        <div class="input_fields_wrap">
                                            <button class="add_field_button btn btn-primary">Tambah Barang</button><br><br>
                                        </div>
                                        <input type="hidden" value="{{ $ruang->user_id }}" name="user_id" class="form-control" required>
                                        <input type="hidden" value="{{ $tanggal_rusak }}" name="tanggal_rusak" class="form-control" required>
                                        <br><br>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                            <button type="submit" class="btn btn-primary">Simpan</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>
      </div>
</div>

@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function() {
            var max_fields      = 100; //maximum input boxes allowed
            var wrapper   		= $(".input_fields_wrap"); //Fields wrapper
            var add_button      = $(".add_field_button"); //Add button ID
        
            var x = 1; //initlal text box count
            $(add_button).click(function(e){ //on add input button click
                e.preventDefault();
                if(x < max_fields){ //max input box allowed
                    
                    let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
                    scanner.addListener('scan', function (content) {
                        var kode = content.substring(0, 10);
                        //$('#barang_id'+x).val(kode);
                        $.get("{{url ('get-data-barang3') }}"+'/'+kode,function(data){
                            $('#nama_barang'+x).val(data.nama);
                            $('#barang_id'+x).val(data.id);
                            var max = document.getElementById("number_id"+x);
                            max.setAttribute("max", data.max)
                            max.setAttribute("placeholder", "Jumlah Maksimal "+data.max)
                        });
                    });
                    Instascan.Camera.getCameras().then(function (cameras) {
                        if (cameras.length > 0) {
                            scanner.start(cameras[0]);
                        } else {
                            console.error('No cameras found.');
                        }
                    }).catch(function (e) {
                        console.error(e);
                    });

                    x++; //text box increment
                    $(wrapper).append('<div><select class="form-control" id="barang'+x+'"><option>Pilih Barang</option>@foreach ($barang as $item)<option value="{{ $item->id}}">{{ $item->barang_detail->barang->barang}} {{ $item->barang_detail->merk}} ({{ $item->jumlah}})</option> @endforeach</select><label for="">Barang</label><input type="hidden" id="ruangan_id'+x+'" name="ruangan_id[]"><input type="text" id="nama_barang'+x+'" name="nama_barang[]" class="form-control" required placeholder="Barang" required readonly><br><input id="number_id'+x+'" type="number" name="jumlah[]" class="form-control" required placeholder="Masukan Jumlah" required></td></tr></table><a href="#" class="remove_field">Remove</a><hr></div>');
                    
                    $("#barang"+x).change(function() {
                        $.get("{{url ('get-data-barang3') }}"+'/'+$(this).val(),function(data){
                            $('#nama_barang'+x).val(data.nama);
                            $('#ruangan_id'+x).val(data.id);
                            var max = document.getElementById("number_id"+x);
                            max.setAttribute("max", data.max)
                            max.setAttribute("placeholder", "Jumlah Maksimal "+data.max)
                        });
                    }); 
                }

            });

            $(wrapper).on("click",".remove_field", function(e){ //user click on remove text
                e.preventDefault(); 
                $(this).parent('div').remove(); 
                x--;
            })
        });
    </script>
@endsection

resources/views/admin/rusakruangan/keranjang/edit.blade.php
@extends('layouts.admin')
@section('title', 'Keranjang Rusak Ruangan')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Keranjang Rusak Ruangan
        </h1>
    </section><br><br>

    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Ubah Data Keranjang Rusak Ruangan</h3>
                </div>

                <div class="box-body" style="overflow-x:auto;">
                    <form action="{{ route('admin.keranjangrusakruangan.update', $data->id) }}" class="form-horizontal" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Ruangan</label>
                            <div class="col-sm-10">
                                <input type="text" value="{{ $data->ruangan->ruang->ruang }}" class="form-control" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Barang</label>
                            <div class="col-sm-10">
                                <input type="text" value="{{ $data->ruangan->barang_detail->barang->barang }} {{ $data->ruangan->barang_detail->merk }}" class="form-control" readonly>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Jumlah</label>
                            <div class="col-sm-10">
                                <input type="number" value="{{ $data->jumlah }}" name="jumlah" class="form-control" placeholder="{{ $data->ruangan->jumlah+$data->jumlah }}" max="{{ $data->ruangan->jumlah+$data->jumlah }}">
                                <small class="text-danger">{{ $errors->first('jumlah') }}</small>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">Tanggal Rusak</label>
                            <div class="col-sm-10">
                                <input type="date" name="tanggal_rusak" value="{{ $data->tanggal_rusak->format('Y-m-d') }}" class="form-control" placeholder="Tanggal Rusak">
                                <small class="text-danger">{{ $errors->first('tanggal_rusak') }}</small>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="btn btn-primary pull-right">Simpan</button>
                            <a href="{{url('admin/keranjangbarangmasuk')}}" class="btn btn-default pull-right">Kembali</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@push('scripts')
    <script type="text/javascript">

        function sum() {
            var txtFirstNumberValue = document.getElementById('txt1').value;
            var txtSecondNumberValue = document.getElementById('txt2').value;
            var result = parseFloat(txtFirstNumberValue) * parseFloat(txtSecondNumberValue);
            if (!isNaN(result)) {
                document.getElementById('txt3').value = result;
            }
        }

    </script>

@endpush
@endsection

resources/views/admin/rusakruangan/keranjang/index.blade.php
@extends('layouts.admin')
@section('title', 'Keranjang Rusak Ruangan')
@section('content')

<div class="container">

    <section class="content-header">
        <h1>
            Keranjang Rusak Ruangan
        </h1>
    </section><br><br>

    <div class="row">
        
        <div class="col-md-4">
            <button class="btn btn-success" data-toggle="modal" data-target="#tambah">Tambah Data</button><br><br>
        </div>
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Keranjang Rusak Ruangan</h3>
                </div>
                <div class="box-body" style="overflow-x:auto;">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Ruang</th>
                                <th>Penginput</th>
                                <th>Barang</th>
                                <th>Jumlah Rusak</th>
                                <th>Tanggal Rusak</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($data as $item)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $item->ruangan->ruang->ruang }}</td>
                                <td>{{ $item->user->name }}</td>
                                <td>{{ $item->ruangan->barang_detail->barang->barang }} {{ $item->ruangan->barang_detail->merk }}</td>
                                <td>{{ $item->jumlah }}</td>
                                <td>{{ $item->tanggal_rusak->format('d-m-Y')}}</td>
                                <td>
                                    @if($item->status==='Dalam perbaikan')
                                        <span class="label label-info">{{ $item->status }}</span>
                                    @else
                                        <span class="label label-warning">{{ $item->status }}</span>
                                    @endif
                                </td>
                                <td align="center" width="200px">
                                    @if($item->status==='Sedang diperbaiki')
                                    <form action="{{ route('admin.keranjangrusakruangan.destroy',$item->id) }}" method="POST">
                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger" alt="Hapus"><i class="fa fa-trash"></i></button>
                                    </form>
                                    @else
                                    <form action="{{ route('admin.keranjangrusakruangan.destroy',$item->id) }}" method="POST">
                                        <a class="btn btn-success" href="{{ route('admin.keranjangrusakruangan.edit',$item->id) }}" alt="Edit"><i class="fa fa-edit"></i></a>

                                        @csrf
                                        @method('DELETE')

                                        <button type="submit" class="btn btn-danger" alt="Hapus"><i class="fa fa-trash"></i></button>
                                    </form>
                                    @endif
                                </td>
                            </tr>
                            @endforeach

                        </tbody>
                    </table>
                </div>
                <div class="box-header with-border" align="center">
                    <a href="/inputrusakruangan" class="btn btn-primary">Masukan Semua Data</a>
                </div>
            </div>
        </div>

        <div id="tambah" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Masukan Data</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="/admin/keranjangrusakruangan/tampil" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="">Pilih Ruang</label>
                                <select name="ruang_id" class="form-control" id="ruang"  style="width:100%">
                                    <option value="" selected disabled>Pilih Ruang</option>
                                    @foreach ($ruang as $ruang)
                                        <option value="{{$ruang->id}}">{{$ruang->ruang}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="">Tanggal Rusak</label>
                                <input type="date" name="tanggal_rusak" class="form-control" required>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Lanjut</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection